Repository NachoXx25/Tienda-UCN-API, pull requests merged in 2025-07, with the labels that each got.

#1 Add the Seeders with Bogus library
  .gitignore
  .husky/pre-push
  Program.cs
  README.md
  Tienda UCN.postman_collection.json
  appsettings.example.json
  src/Domain/Models/.gitkeep
  src/Domain/Models/Brand.cs
  src/Domain/Models/Cart.cs
  src/Domain/Models/CartItem.cs
  src/Domain/Models/Category.cs
  src/Domain/Models/Image.cs
  src/Domain/Models/Order.cs
  src/Domain/Models/OrderItem.cs
  src/Domain/Models/Product.cs
  src/Domain/Models/Role.cs
  src/Domain/Models/User.cs
  src/Infrastructure/Data/.gitkeep
  src/Infrastructure/Data/DataContext.cs
  src/Infrastructure/Data/DataSeeder.cs
  src/Infrastructure/Migrations/20250722022020_InitialMigrate.Designer.cs
  src/Infrastructure/Migrations/20250722022020_InitialMigrate.cs
  src/Infrastructure/Migrations/20250722190633_OrderItemProperties.Designer.cs
  src/Infrastructure/Migrations/20250722190633_OrderItemProperties.cs
  src/Infrastructure/Migrations/DataContextModelSnapshot.cs
Labels: feat, refactor, fix

#3 New Auth Diagrams
  Docs/Auth/1_Register.md
  Docs/Auth/2_VerifyCode.md
  Docs/Auth/3_ResendCode.md
  Docs/Auth/4_Login.md
Labels: documentation

#4 Login Feature with identity operations in user repository class and updated the appsettings configurations
  Program.cs
  appsettings.Development.json
  appsettings.example.json
  src/Application/Services/Implements/UserService.cs
  src/Infrastructure/Repositories/Implements/UserRepository.cs
  src/Infrastructure/Repositories/Interfaces/IUserRepository.cs
  src/api/Middlewares/ExceptionHandlingMiddleware.cs
Labels: documentation, refactor

#5 Register, verify email and resend email verification features
  Program.cs
  README.md
  Tienda UCN.postman_collection.json
  Tienda-UCN-api.csproj
  appsettings.example.json
  src/Application/DTO/AuthDTO/RegisterDTO.cs
  src/Application/DTO/AuthDTO/ResendEmailVerificationCodeDTO.cs
  src/Application/DTO/AuthDTO/VerifyEmailDTO.cs
  src/Application/Mappers/MapperExtensions.cs
  src/Application/Mappers/UserMapper.cs
  src/Application/Services/Implements/EmailService.cs
  src/Application/Services/Implements/UserService.cs
  src/Application/Services/Interfaces/IEmailService.cs
  src/Application/Services/Interfaces/IUserService.cs
  src/Application/Templates/Email/VerificationCode.html
  src/Application/Templates/Email/Welcome.html
  src/Application/Validators/.gitkeep
  src/Application/Validators/BirthDateValidationAttribute.cs
  src/Application/Validators/RutValidationAttribute.cs
  src/Domain/Models/User.cs
  src/Domain/Models/VerificationCode.cs
  src/Infrastructure/Data/DataContext.cs
  src/Infrastructure/Data/DataSeeder.cs
  src/Infrastructure/Data/Migrations/20250729155335_InitialCreate.Designer.cs
  src/Infrastructure/Data/Migrations/20250729155335_InitialCreate.cs
  src/Infrastructure/Data/Migrations/20250731013147_ExpirationDateOfVerificationCode.Designer.cs
  src/Infrastructure/Data/Migrations/20250731013147_ExpirationDateOfVerificationCode.cs
  src/Infrastructure/Data/Migrations/DataContextModelSnapshot.cs
  src/Infrastructure/Migrations/20250722022020_InitialMigrate.Designer.cs
  src/Infrastructure/Migrations/20250722190633_OrderItemProperties.cs
  src/Infrastructure/Migrations/20250723021832_IdentityRoleManagement.cs
  src/Infrastructure/Repositories/Implements/UserRepository.cs
  src/Infrastructure/Repositories/Implements/VerificationCodeRepository.cs
  src/Infrastructure/Repositories/Interfaces/IUserRepository.cs
  src/Infrastructure/Repositories/Interfaces/IVerificationCodeRepository.cs
  src/api/Controllers/AuthController.cs
  src/api/Middlewares/ExceptionHandlingMiddleware.cs
Labels: documentation, feat, refactor, fix
